jembi/openhim-core-js

- src/tcpAdapter.coffee
- test/integration/tcpIntegrationTests.coffee
* Checked to see if the socket is writable before writing to it in case the client has disconnected. (#272)
* Added an error listener so that connection errors do not crash the HIM. (#315)
> Handle tcp errors and don't write to closed sockets

- src/alerts.coffee
- src/api/channels.coffee
- src/api/tasks.coffee
- src/middleware/authorisation.coffee
- src/model/channels.coffee
- src/polling.coffee
- src/tcpAdapter.coffee
- test/integration/channelsAPITests.coffee
- test/integration/tasksAPITests.coffee
- test/unit/alertsTest.coffee
- test/unit/authorisationTest.coffee
- test/unit/pollingTest.coffee
- test/unit/tcpAdapterTest.coffee
Closes #324 
@rcrichton if you could please review?
Tested everything through the API and seems to be working fine.
Currently when someone tries to delete a channel, it will first check to see if there are any linked transactions. If not it will still properly remove the channel (useful if they added a bad channel or something), otherwise it sets the flag.
> Channels deleted flag

- config/default.json
- src/server.coffee
This only applies to the HTTP, HTTPS and API server since the polling, rerun and TCP adapters are already bound to localhost.
Closes #385.
> Add the option to specify a bind address

- src/middleware/rerunBypassAuthorisation.coffee
I am seeing the following error on staging when rerunning a transaction:
```
TypeError: Cannot read property 'length' of undefined
at containsMultiplePrimaries (/opt/openhim-core-js/lib/middleware/router.js:38:29)
at sendRequestToRoutes (/opt/openhim-core-js/lib/middleware/router.js:155:7)
at exports.route (/opt/openhim-core-js/lib/middleware/router.js:469:10)
at Promise.apply (/opt/openhim-core-js/node_modules/q/q.js:1107:26)
at Promise.promise.promiseDispatch (/opt/openhim-core-js/node_modules/q/q.js:748:41)
at /opt/openhim-core-js/node_modules/q/q.js:1333:14
at flush (/opt/openhim-core-js/node_modules/q/q.js:110:17)
at process._tickDomainCallback (node.js:381:11)
```
This correlates to https://github.com/jembi/openhim-core-js/blob/master/src/middleware/router.coffee#L19 in the …
> Look up authorised channel on rerun

- src/model/transactions.coffee
This PR relates to issue: #410 
Some channels or orchestrations don't always have request.path or request.method value so the rerun update function didn't execute correctly and failed to update.
> Updated model required field for path and method

- infrastructure/development/env/openhim-core-js.pp
@rcrichton just a quick one: disabled makeinstall for node in puppet. This improves vagrant startup times drastically
> Disabled make-install for node.js in puppet

- src/api/transactions.coffee
Found this bug in transactions -> find by ID. 
The result returned is not an array but rather an object when searching for a specific record. If the result is null (not found) then a server error is thrown on .length. 
Replicate: View a valid transaction details. Change the URL to reference an invalid transaction ID and the labels are still show as well as an error in console.
> Minor fix to transaction API - getTransactionById()

- src/model/audits.coffee
@rcrichton mind taking a look at this? I've added syslog info to the audit schema. I found a [good library](https://www.npmjs.com/package/glossy) to do the parsing and took these fields straight from what it gives us.
cc @BMartinos @debonair
> Added syslog information to the audit model

- src/middleware/visualizer.coffee
- src/model/events.coffee
insert.
@rcrichton if you could please take a look? I saw in the flame graph that the visualizer usage was quite high, not super high, but still. These few improvements shave off a few ms.
It seems mongoose's `create` just loops through the array and saves each document, rather than doing a proper batch insert. If switched this out with a driver batch insert. This mean we're not doing any validations, but seems okay to me since you can't add to this collection from the API, only from this code. To reflect our lack of validation, I took out the `require`s in the model.
> Visualizer events: async processing. Replaced create with batch driver

- src/api/tasks.coffee
- test/integration/tasksAPITests.coffee
@rcrichton a quick additional feature following #434 - this allows a task to be added in 'paused' state so that it doesn't begin running immediately.
> OHM-117: Allow a task to be added in a 'Paused' state

- src/api/transactions.coffee
Prevent the HIM from crashing when updating a transaction with some operation other than a push to the routes array.
> Check that updates.$push is defined

- config/default.json
- config/development.json
- config/test.json
- src/api/channels.coffee
- src/api/restart.coffee
- src/server.coffee
- src/tcpAdapter.coffee
- test/integration/channelsAPITests.coffee
- test/integration/restartAPITests.coffee
- test/unit/serverTest.coffee
Closes #405 
This PR allows the OpenHIM to use the cluster API. This will share all servers with the workers, both TCP and HTTP, so,  this allows us to cluster even with a single config file.
There is a bug in node preventing me from clustering the UDP sockets (See joyent/node#9261) so those don't get clustered yet. The first worker to get to the server up hosts it.
Use as follows: `node --harmony lib/server/js --cluster=auto` - or replace auto with a number of workers.
@devcritter could you please review this?
> Cluster API integration to allow TCP ports to be shared

- package.json
- src/api/audits.coffee
- src/api/authentication.coffee
- src/api/channels.coffee
- src/api/clients.coffee
- src/api/contactGroups.coffee
- src/api/keystore.coffee
- src/api/mediators.coffee
- src/api/restart.coffee
- src/api/tasks.coffee
- src/api/transactions.coffee
- src/api/users.coffee
- src/api/visualizer.coffee
- src/middleware/authorisation.coffee
- src/middleware/pollingBypassAuthentication.coffee
- src/middleware/router.coffee
- src/middleware/tcpBypassAuthentication.coffee
- src/middleware/visualizer.coffee
- test/integration/e2eIntegrationTests.coffee
- test/unit/authorisationTest.coffee
Closes #318 
@rcrichton if you could please take a look? @bausmeier it would be useful if you could take a look as well, seeing as you picked this up originally?
Replaced all the status string with codes. Used ack to figure out what statuses we're using (`ack --type coffeescript -o 'status ?= ?(.*)'`) and a combination of ack and perl to substitute the matches (using the approach outline in the first answer [here](http://stackoverflow.com/questions/4792561/how-to-do-search-replace-with-ack-in-vim)).
I *think* I've got everything. The tests are passing and my test transactions are happy.
> OHM-61: Replaced http status strings with codes for koa compatibility

- src/server.coffee
By comparing heap snapshots I found that references to closed `TLSSocket`s are being retained by the `activeApiConnections` object. After some investigation I found that the close listener that is being added in `trackConnection` is never called. It turns out the reference that is passed to the `connection` event on HTTPS servers is to the underlying `net.Socket` and not to the `TLSSocket` itself. For some reason the `close` event is not emitted on the underlying socket so the listener is never being called and the references aren't being cleaned up. By listening to the `secureConnection` event instead of the `connection` event we get a reference to the `TLSSocket` which does emit the `close` event.
> Fix memory leak

- src/middleware/router.coffee
This is for backwards compatibility with mediators which return status codes as strings. This used to work before we upgraded koa.
@rcrichton Please take a look at this.
> Parse response status to an int if it is a string

- infrastructure/development/env/Vagrantfile
@rcrichton just upgraded the vagrant box. Took out the timesync hack - _seems_ okay without it on this box, but will reinvestigate if issues crop up.
> Vagrant: Upgraded to trusty64 box

- package.json
Closes #512 
Skipping CR as this is just a one liner package fix.
> Issue #512: Set mongoose to 4.0.2

- infrastructure/development/env/Vagrantfile
- src/server.coffee
When send a audit message via TCP or TLS and no length is supplied then the request fails silently.
credit to @bausmeier for tracking down the issue
> Audit server bug

- infrastructure/development/env/Vagrantfile
With the updated vagrant file, the bridged connection (eth1) no longer existed.
> Added network bridge setting in updated Vagrant file

- src/model/mediators.coffee
@rcrichton this seems to do the trick. the issue is that the channel schema has a unique index on it, and when mediators haven't got default channel config, a null key was added to this index.
> Fixes #545: defaultChannelConfig.name sparse index

- src/model/channels.coffee
- src/model/mediators.coffee
- test/integration/channelsAPITests.coffee
- test/integration/mediatorAPITests.coffee
Closes #545 for real this time
@rcrichton if you could please review? The problem was that the index definition in the channel schema was propagated through to the mediator schema when it reused it - i refactored it a bit so as to keep the index definition out of the channel def. The mediator collection therefore won't even have an index on channel.name anymore, which i think is correct.
> Fixes #545: Refactored channels schema definition

- docs/dev-guide/mediators.md
- src/api/mediators.coffee
- src/model/mediators.coffee
- test/unit/mediatorsAPITest.coffee
@rcrichton what do you think?
There's a lot we can do e.g. with regards to the dynamic config for the file queue but I think this map is already really useful and would be great to keep as is. Therefore I think whatever we look into next should be done in addition to this as another config type/plugin architecture/whatever.
> Mediators: Added support for 'map' config type

- src/model/transactions.coffee
- test/unit/rerunUpdateTransactionTask.coffee
@hnnesv could you please review this for me. Also @napiergit could you have a look and also try out this branch with the transactions that you were having this problem with and let me know if this fixes it for you.
Details:
Mongoose populates object in the schema with empty objects and empty
arrays by default. This causes the request object to be an empty object
even when no request property was even supplied. This then causes
Mongoose's validation to fail as it expects request objects to have a
.timestamp property.
Adding `required: false` to the schema seems to stop Mongoose from
populating it as an empty object.
See https://github.com/jembi/openhim-console/issues/356
> Fix validation issues during rerun

- docs/tutorial/1-getting-started.md
- docs/tutorial/3-creating-a-passthrough-mediator.md
Hey @rcrichton looks like the resource links are broken
Not sure if this is the correct way to specify them! This works when I build the docs locally though.
Thanks to @psmatsinhe for pointing these out
> Changed to relative links for _static resources

- src/middleware/events.coffee
- test/globalConfig.coffee
- test/integration/auditingIntegrationTests.coffee
- test/integration/e2eIntegrationTests.coffee
- test/integration/logsAPITests.coffee
- test/integration/transactionsAPITests.coffee
- test/unit/routerTest.coffee
- test/unit/tasksTest.coffee
- test/unit/upgradeDBTest.coffee
The factor is increased when travis is detected to be running the tests.
This allows us to have quick setTimeout values when testing locally,
however, these are dilated when run on travis. Travis is slower due to
it being a virtual environment.
> OHM-243 Apply a factor to setTimeout calls in testing

- infrastructure/development/env/Vagrantfile
- infrastructure/development/env/openhim-core-js.pp
@rcrichton a quick one - this change allows vagrant to use mongo 3.2
> Vagrant: use mongo 3.2

- package.json
- src/api/metrics.coffee
@rcrichton a quick bug fix - seems moment (annoyingly) starts months on 0, so the timestamps were one month ahead in the results.
> Metrics: timestamp fix

- infrastructure/development/env/openhim-core-js.pp
@rcrichton a quick one - this just adds a build dep so that the native kerberos module compiles correctly (mongodb)
> Vagrant: add krb-dev dependency

- packaging/targets/trusty/debian/control
@rcrichton I added them as recommends rather depends. Install recommends is true by default anyway and this at least gives the option for implementers who for some reason don't want to enable native compiling.
> Packaging: Include build deps in recommends

- docs/dev-guide/api-ref.md
- src/api/metrics.coffee
Mongodb always returns time values as UTC.
> OHM-336 Fix tz returned for metrics

- src/middleware/router.coffee
- src/server.coffee
The OpenHIM crashed when using an environment variable to configure the router timeout because the value is a string.
To reproduce start the OpenHIM with `router_timeout=120000 npm start` and make a request to the router.
Casting the config value to a number fixes the problem.
> Fix configuration of router timeout using an environment variable

- config/config.md
The config.md file has two typos in the description for
"router.httpsPort" and "router.httpPort". I have added the missing
word("forward") in both descriptions.
> Fix config.md docs

- src/config/config.js
Sometimes, depending on environment variable order, the NODE:ENV key in
nconf was being overwritten by a NODE environment variable. This was
happening particularly in workers. This is probably why nconf uses ':'
as a separator instead of '_' which we are using. Changing to not use
'_' would introduce breaking changes so this change rather reads the
environment directly from process.env.
> Fix environment reading in config

- src/api/transactions.js
- test/integration/transactionsAPITests.js
The expected structure of the query parameters was different to what is
actually being sent by the console.
> OHM-673 Fix channel filtering for non-admins

- docs/roadmap.md
Users can't get to the old URL on the confluence unless they are part of Jembi...
> Update the URL to the Roadmap on the WIKI

- src/api/authentication.js
- test/unit/apiAuthenticationTest.js
After creating a release for the basic authentication support I realised that we need to be able to configure the authentication types using environment variables. This PR adds support for that.
It can be tested by starting the OpenHIM core with `api_authenticationTypes="[\"basic\"]" npm start`.
> Support configuring authentication types as JSON

- src/contentChunk.js
- src/middleware/messageStore.js
- src/middleware/router.js
This is the function that will be used for sending secondary routes requests. It uses some of the functionality that is used in the function for sending the primary route requests. Refactoring will be done later on to apply the DRY principle. The function has been added to the 'sendRequest' function, which is the wrapper for the functions that send the requests. A flag has been added to use the function for secondary routes when route is secondary.
OHM-800
> create a function for sending an http request

- src/middleware/router.js
This was due to the change to read an incoming stream instead of a full payload.
This change takes the reponse.body stream and builds up a string with all the supplied chuncks before setting the koa response.
We need to read in the entire payload here to process the mediator medatadata being supplied in the response
> Bug fix: Responses in Mediator format was failing the transaction

- src/metrics.js
- src/middleware/messageStore.js
- src/middleware/router.js
- src/tasks.js
Addresses an issue where, under load, metrics were not being captured for all transactions (~2 out of 200). 
The issue is caused by the metrics update routine being called after the initial request information is persisted, but before the initial response information is available in the db (the metrics update required a responseTime for calculation, which was not available at that point). 
This change updates the calculation to require the response end-time instead of start-time, making the calculation more accurate, and also forces the setFinalStatus update to wait for completeResponse to complete before running.
> Bug fix transaction sequence metrics capture

- src/koaMiddleware.js
- src/middleware/authorisation.js
- src/middleware/requestMatching.js
- src/middleware/router.js
- src/middleware/streamingReceiver.js
- src/middleware/streamingRouter.js
- test/unit/requestMatchingTest.js
Request matching for content bodies was removed for the initial conversion to streaming. 
Now, this functionality is being added back, based on input request being a stream.
> OHM-831 Add back content matching for request bodies

- src/middleware/streamingRouter.js
When a channel's responseBody property (which determines whether the response body is stored) is set to false or undefined, the client should still get a response. This issue has been resolved in this commit and the authentication tests are now passing. A function that is no longer used has also been removed
OHM-896
> fix responding to the client (responseBody -false)

- src/middleware/streamingReceiver.js
The app was storing request bodies even when the channel had been configured not to store the bodies
OHM-898
> fix the storing of request bodies

- src/middleware/router.js
Responses from openhim medaitors have to be handled diffrently. The response body contains orchestrations etc, which have to be extracted from the body. This is done for the primary route and was not being done for the secondary routes, resulting in errors
OHM-906
> fix the handling of openhim mediator responses

- README.md
Updated references to node 12 as this is our latest supported LTS version. A newer version of MongoDB can now be used.
Removed the "deployments" section as this is no longer valid. The openhim-docker repository handles the building of the images and isnt trigger on pushing new code to the master branch
OHM-941
> OHM-941: Update README documentation

- package.json
Version bumped to 5.4.0
This version should be replacing v5.3.0 as that version was incorrectly released. To avoid confusion, we are bumping this verion again with a minor version update
TRACE-137
> Release new version of the OpenHIM Core

- packaging/build-docker-centos-rpm.sh
OpenHIM core now builds on Nodejs 12. This fix allows the build to succeed on the correct version of NodeJS
TRACE-137
> Updated NodeJS version to use 12

- src/api/transactions.js
- test/integration/transactionsAPITests.js
Transaction bodies are stored separately and can be very large. We have
rewritten the OpenHIM to stream data instead of consolidating before
orchestrating.
We are implementing this same principle with interactions with the api
to improve response times.
If a request is made for transactions, a secondary request must be made
for the potentially large transaction bodies which will then be streamed
to the requester.
OHM-1035
> OHM-1035 Remove logic that added transaction bodies

- package.json
To indicate the dependecy updates
and the bug fix on the clientId/role name not allowed to be the same
> Updated package version with a patch increase

- src/middleware/tlsAuthentication.js
The success message should only be logged out when tls authentication is successful.  Logging out the message was causing an error to be thrown when tls auth fails
DATO-8
> fix tls authentication issue

- src/middleware/tlsAuthentication.js
the line should be placed after the authentication. Placing it before was causing an error to be thrown when tsl auth failed
DATO-8
> move the line for logging out success message

- package-lock.json
- src/middleware/requestMatching.js
- test/unit/requestMatchingTest.js
Reverts jembi/openhim-core-js#1101
Test failing - don't have time to fix it right now
> Revert "Issue #1100: Request matching should include HTTP methods"

- src/middleware/router.js
Logic has been added to ensure that a response is added to the ctx.routes obect, which is checked when setting the transaction status. Errors in secondary routes were not being considered when the status was being set resulting in a status of 'successful' instead of 'completed with errors'
OHM-1080
> Fix openhim transaction status

- .github/workflows/master.yml
- .github/workflows/tags.yml
- .nycrc.json
- test/unit/messageStoreTest.js
Failed to fetch docker image for MacOS (missing M1 arm64 platform build).
Github action config was updated according to docker documentation to publish multi-platform images : 
https://docs.docker.com/build/ci/github-actions/multi-platform/
Related PRs : https://github.com/jembi/openhim-console/pull/607
> feat: add docker support for arm64 platform

- src/model/users.js
- test/unit/usersTest.js
Updating the password does not update the old hash value in passport collection. 
How to reproduce  :
- Open OpenHIM (fresh install)
- First login with root@openhim.org / openhim-password
- Reset password (BUG : passwordHash stays the same)
- Run the openhim mapping mediator -> fails to authenticate.
> fix: update old password hash (deprecated token strategy)

- config/config.md
- config/default.json
- package.json
- src/koaApi.js
I was deploying OpenHIM for Indonesia on Google Cloud Run. OpenHIM is served behing a proxy that issues the SSL.
It was impossible to connect through OpenHIM console. When checking the logs I found the following error : "Error: Cannot send secure cookie over unencrypted connection"
Basically, you cannot set "secure=true" for the cookie and then serve it in HTTP. For that we needed that option to trust that the proxy.
Check : https://github.com/koajs/koa/issues/974
NOTE : This should be tested in platform.
> fix: trust proxy ssl to forward session cookie

- package-lock.json
- package.json
- src/api/apps.js
- src/koaApi.js
- src/model/apps.js
- test/integration/appsAPITests.js
This adds the apps crud endpoints
> Tb 151 apps endpoints

- src/middleware/router.js
The reason the header were not attached is due to the condition on line 59 of router.js, because the object returned from Kafka did not have a "headers" property this check always evaluated to false so the Transaction ID is never added.
> adding empty header obj to pass condition

- config/config.md
- src/passport.js
This pull request adds the ability to specify an optional Openid connect provider issuer url in the config file. If provided, passport.js will use this url instead of the api url. This change ensures that the correct issuer url is used when using a proxy.
> Add optional Openid connect provider issuer url to config and update passport.js to use it

- package.json
- src/model/apps.js
- test/integration/appsAPITests.js
- test/unit/appsTest.js
This pull request proposes modifying the Apps schema's type attribute to:
- New enum values: Replace `['link', 'embedded']` with `['internal', 'external', 'esmodule']`.
However, I'd like to open a discussion about alternative naming options :
- `built-in `: OpenHIM Console core module or internal pages
- `shortcut`: link to an external web page or app
- `in-browser-module`: link to one of Jembi's or third-party bundled ESModules
> Update enum values for OpenHIM Apps type

- package-lock.json
- package.json
- src/middleware/router.js
- test/unit/routerTest.js
Resolves Issue: Missing request body in PATCH requests #1217
> Add support for PATCH requests in router middleware
