jembi/openhim-core-js

infrastructure/development/env/Vagrantfile
Closes #329 
@rcrichton if you could please take a quick glance? Maybe @psbrandt too if you have a moment?
A bit hacky, but not too sure if there's a more elegant way...
=> OHM-23: Vagrant -> added more strict time sync

README.md, resources/openhim-core.conf
Closes #303 
@devcritter please can you review this?
=> Added upstart config

src/api/channels.coffee, src/tcpAdapter.coffee, test/integration/channelsAPITests.coffee, test/unit/tcpAdapterTest.coffee
=> Fetch the channel from the db with each request

infrastructure/deployment/env/openhim-core-js.pp, infrastructure/development/env/openhim-core-js.pp
Hey @devcritter do you mind just reviewing this for me. Thanks
=> Updated puppet script to include mongo client and set timeout to zero

src/model/contactGroups.coffee
This PR relates to issue https://github.com/jembi/openhim-console/issues/210 on console. Added unique tag for contactGroups collection to avoid duplicates.
=> OHM-24: added unique tag to contactGroups collection

README.md, src/api/mediators.coffee, src/api/tasks.coffee, src/api/visualizer.coffee, src/utils.coffee
This PR relates to issues: 
#349
#346
#344
=> Martin conversions

src/api/channels.coffee
Closes #341 
@devcritter could you review this to? Else feel free to hand it off if I've given you too much CR :)
=> OHM-45: Converted api/channels.coffee generators to coffeescript.

src/koaMiddleware.coffee, src/restart.coffee
Closes #351 
Closes #352 
@rcrichton if you could please take a look?
=> Koa middleware restart to coffee

infrastructure/deployment/env/openhim-core-js.pp, infrastructure/development/env/openhim-core-js.pp
@rcrichton bumped the puppet scripts to stable
=> Updated to stable node

src/api/authentication.coffee, src/api/clients.coffee
=> OHM-44 OHM-46 Convert clients and authentication

src/api/transactions.coffee
Closes #347 
@rcrichton if you could please take a look?
=> OHM-51: converted transactions to coffee

src/api/statsd.coffee
=> fixed retrieve stats from statsd

src/api/users.coffee
Closes #348 
@rcrichton if you could please take a look?
=> OHM-52: Converted api/users to coffee

.travis.yml, package.json
Also cleaned up the prepublish and test scripts.
=> Add travis build target for node.js 0.12 and io.js

src/api/contactGroups.coffee, src/api/keystore.coffee, src/api/mediators.coffee, src/api/tasks.coffee, src/api/visualizer.coffee
This PR relates to issue #343. 
Some additional changes to the other generators as well. ( code consistency )
=> OHM-47: Updated javascript generators to coffeescript

src/api/metrics.coffee
@rcrichton please review closes #345
=> converted metrics to coffee-script

package.json, src/middleware/basicAuthentication.coffee
Closes #387 
@rcrichton a quick one...
=> Switched to js bcrypt module

src/api/users.coffee, src/api/visualizer.coffee
@rcrichton if you could please review? We just found some errors testing the visualizer.
=> Found some errors post convert-javascript

src/api/transactions.coffee
@devcritter Please have a quick look.
=> More post javascript conversion fixes

src/api/transactions.coffee
There were some logger message mistakes in the transactions API. Updated the logger text accordingly
=> Corrected logging messages for transactions

config/default.json
True for both auth methods and false for statsd @rcrichton review s'il vous plaît
=> changed default config options 

config/development.json, resources/testCurlCmds.md, src/middleware/authorisation.coffee, src/middleware/basicAuthentication.coffee, src/middleware/tlsAuthentication.coffee, test/resources/tlsTestServer.js, test/unit/authorisationTest.coffee
Hey @devcritter these are some authentication fixes and edits that I did while running the TLS tests. Please can you review these for me?
=> Auth fixes and edit

.travis.yml, package.json
=> Misc package edits

src/api/worker.coffee, src/middleware/rerunBypassAuthentication.coffee
@devcritter or @rcrichton please review
=> fixes public channel rerun closes #408

README.md, package.json
=> Updated readme for 1.1 release

config/default.json, config/development.json, infrastructure/development/env/Vagrantfile, package.json, src/auditing.coffee, src/model/audits.coffee, src/server.coffee, test/integration/auditingIntegrationTests.coffee, test/integration/channelsAPITests.coffee, test/integration/clientsAPITests.coffee, test/integration/contactGroupsAPITests.coffee, test/integration/e2eIntegrationTests.coffee, test/integration/generalAPITests.coffee, test/integration/keystoreAPITests.coffee, test/integration/mediatorAPITests.coffee, test/integration/metricsAPITests.coffee, test/integration/restartAPITests.coffee, test/integration/tasksAPITests.coffee, test/integration/tcpIntegrationTests.coffee, test/integration/transactionsAPITests.coffee, test/integration/usersAPITests.coffee, test/unit/auditingTest.coffee, test/unit/serverTest.coffee
=> Atna udp interface

package.json, src/koaMiddleware.coffee, src/middleware/authorisation.coffee, src/middleware/basicAuthentication.coffee, src/middleware/messageStore.coffee, src/middleware/pollingBypassAuthentication.coffee, src/middleware/pollingBypassAuthorisation.coffee, src/middleware/proxy.coffee, src/middleware/rerunBypassAuthentication.coffee, src/middleware/rerunBypassAuthorisation.coffee, src/middleware/rerunUpdateTransactionTask.coffee, src/middleware/retrieveTCPTransaction.coffee, src/middleware/router.coffee, src/middleware/stats.coffee, src/middleware/tcpBypassAuthentication.coffee, src/middleware/tlsAuthentication.coffee, src/middleware/visualizer.coffee
Closes #426 
@devcritter could you please review this for me.
=> Report app metrics

src/api/transactions.coffee, src/middleware/messageStore.coffee, test/integration/transactionsAPITests.coffee
Collects metrics for async transactions
=> Updated transaction metrics

src/server.coffee, test/integration/auditingIntegrationTests.coffee
This PR relates to issue: https://github.com/jembi/openhim-core-js/issues/374
=> OHM-66: Added ATNA TLS/TCP interface with test - TLS Tests still failing

config/default.json, config/test.json, src/middleware/authorisation.coffee, src/middleware/router.coffee, src/middleware/visualizer.coffee, src/model/clients.coffee, src/utils.coffee
Closes #432 
Closes #431 
Closes #430 
Closes #429
Closes #428 
@rcrichton mind taking a look? Thanks
=> Performance optimizations

src/api/channels.coffee
Found this bug when trying to add a duplicate channel ( Through the export feature )
=> Channel Add bug fix

src/middleware/authorisation.coffee, test/unit/authorisationTest.coffee
This PR relates to issue: https://github.com/jembi/openhim-core-js/issues/443
=> Authorise Channel Bug Fix

src/api/tasks.coffee
@rcrichton check for https://github.com/jembi/openhim-console/pull/263
=> Check and remove _id

src/api/contactGroups.coffee, test/integration/contactGroupsAPITests.coffee
=> Alert groups w channels

src/api/tasks.coffee, src/model/tasks.coffee, src/tasks.coffee, test/integration/tasksAPITests.coffee, test/unit/rerunUpdateTransactionTask.coffee, test/unit/tasksTest.coffee
This PR relates to issue: https://github.com/jembi/openhim-console/issues/255
Added filtering and pagination additions to the getTask() and getTasks() API function. Updated tests. Found a bug in src/tasks.coffee that broke the server
=> Tasks pagination

src/api/transactions.coffee
This PR relates to issue: https://github.com/jembi/openhim-core-js/issues/436
=> Tasks based on filters

config/default.json, src/api/authentication.coffee, test/integration/generalAPITests.coffee
Closes #452 
@rcrichton if you could please review?
=> OHM-126 #452: Made auth window configurable.

package.json, src/contact.coffee
Closes #319 
@rcrichton if you could please review? It's luckily a pretty easy upgrade.
=> OHM-62 #319: Upgraded nodemailer

src/server.coffee
This PR relates to issue: https://github.com/jembi/openhim-core-js/issues/456
Credit goes to @bausmeier and @debonair for showing where to added the timestamp setting
=> OHM-136: Added timestamp to logger

src/reports.coffee
Fixed issue with daily and weekly reports
=> fixed plaintext function

README.md, config/config.md, package.json, src/api/keystore.coffee, src/model/alerts.coffee, src/model/audits.coffee, src/model/channels.coffee, src/model/clients.coffee, src/model/contactGroups.coffee, src/model/events.coffee, src/model/keystore.coffee, src/model/mediators.coffee, src/model/tasks.coffee, src/model/transactions.coffee, src/model/users.coffee, src/tasks.coffee, test/integration/auditingIntegrationTests.coffee, test/integration/keystoreAPITests.coffee, test/testUtils.coffee, test/unit/alertsTest.coffee, test/unit/reportsTest.coffee, test/unit/tasksTest.coffee
Closes #458 
I've added a doc page with details about config option becasue: 1) We need it and 2) I needed to explain that you need the `replicaSet` option in the URL now with mongoose 4.0 as it used the node mongo driver v2.0.
=> Mongoose 4.0 - OHM-135

src/middleware/router.coffee, src/server.coffee
This PR relates to issue: #460
=> OHM-134: Added error checking for server and client

src/api/certificateAuthority.coffee, src/api/keystore.coffee, src/middleware/tlsAuthentication.coffee, src/model/clients.coffee, src/model/dbVersion.coffee, src/model/keystore.coffee, src/server.coffee, src/upgradeDB.coffee, test/globalConfig.coffee, test/integration/certificateApiTests.coffee, test/integration/clientsAPITests.coffee, test/integration/e2eIntegrationTests.coffee, test/integration/keystoreAPITests.coffee, test/testUtils.coffee, test/unit/tlsAuthenticationTest.coffee, test/unit/upgradeDBTest.coffee
Closes #419 
Hey @bausmeier could you review this for me in Hannes' absence?
=> Client cert lookup

infrastructure/development/env/openhim-core-js.pp
@rcrichton yet another quick ad-hoc PR :) This just adds git as a dependency for those npm packages that need it.
=> Added git install dependency.

src/upgradeDB.coffee
Hey @rcrichton ran into a problem while doing a fresh install (vagrant). Just added a check to see if the keystore exists.
=> Added check to see if keystore exists

config/default.json, src/reports.coffee, src/server.coffee, test/unit/reportsTest.coffee
=> closes #483

.travis.yml
@devcritter quick one, could you have a look at this please?
=> Autodeply only when on master branch.

src/api/keystore.coffee, test/integration/keystoreAPITests.coffee
@debonair could you review this for me please?
=> Keystore validity return false if a protected key is tested without a pasphrase

src/polling.coffee, src/server.coffee
=> Polling last run

src/middleware/router.coffee
@devcritter @rcrichton please review this closes #498
=> hardened async routes with error handling

src/middleware/messageStore.coffee, src/middleware/visualizer.coffee
=> fixed issues with status closes #500 #501 #502

src/middleware/messageStore.coffee, src/middleware/router.coffee, src/model/transactions.coffee, test/unit/messageStoreTest.coffee
Closes #497
@devcritter could you have a look at this? Also, while working on this I realised something, see #505.
=> Adds host and port metadata for routes.

src/upgradeDB.coffee
=> Fixes #510

infrastructure/development/env/Vagrantfile, infrastructure/development/env/openhim-core-js.pp
Fixed the puppet mongodb module version to 0.10.0.
@rcrichton if you could please take a look? just some vagrant updates.
=> Updated vagrantfile to v2 and bumped the box mem.

.travis.yml, package.json, src/api/authentication.coffee, src/middleware/router.coffee
=> Fix the build

src/alerts.coffee
=> Fixed lint errors.

docs/dev-guide/api-ref.md, docs/dev-guide/mediators.md, package.json, src/api/mediators.coffee, src/koaApi.coffee, src/model/mediators.coffee, test/integration/mediatorAPITests.coffee, test/unit/mediatorsAPITest.coffee
Closes #524 and closes #523 
@devcritter could you please review this for me?
=> Mediator heartbeats

src/model/clients.coffee
Closes #535 
@rcrichton does this look okay to you? Can you think of anything else that would be useful to add?
=> Issue #535 OHM-194: Added additional fields to the client model

src/model/mediators.coffee
=> Fixed the config param model

src/api/mediators.coffee
=> Fixes #548: Return empty on heartbeat with no config response

src/model/mediators.coffee, test/unit/mediatorsAPITest.coffee
Hey @devcritter could you please review?
Closes #555 and closes #547
=> Mediator model changes for better display on the console

.gitignore, src/api/mediators.coffee, test/integration/mediatorAPITests.coffee
Closes #550 
@devcritter could you have a look please.
=> Only updates new mediator config values, preserves old config on mediator updates

.travis.yml, package.json, src/api/users.coffee
=> User audit

package.json, src/api/mediators.coffee, src/server.coffee, test/integration/auditingIntegrationTests.coffee
=> Add actor start and stop audits

docs/dev-guide/api-ref.md, src/api/heartbeat.coffee, test/integration/heartbeatAPITest.coffee
=> OHM-204 Issue #576: Added mediators to heartbeat

src/api/users.coffee
@rcrichton a quick one. This logging gets a bit hectic with lots of mediators all sending heartbeats!
=> Auditing: changed logging to debug level

src/api/channels.coffee
Closes #587 
@rcrichton a quick one
=> Fixes #587: Use the correct channel object

src/api/transactions.coffee, src/middleware/events.coffee, test/integration/transactionsAPITests.coffee
Closes #596 
@rcrichton if you could please review? we now have alerting and visualization on async updates
=> Issue #596: Store events on add/update transaction

docs/dev-guide/mediators.md, src/api/mediators.coffee, src/model/mediators.coffee, src/utils.coffee, test/integration/mediatorAPITests.coffee, test/unit/mediatorsAPITest.coffee
Closes #591 
Closes #592 
For repeating fields, rather that something like `repeats: 3` I instead opted to define it as `array: true`. I think it's a simpler option, but for now there is no max limit on the size of the array. I think if it comes up, we can figure out a solution for it, but I think it's easier to work with like this.
=> Config struct repeats

config/config.md, config/default.json, docs/user-guide/auditing.md, docs/user-guide/index.rst, src/api/mediators.coffee, src/api/users.coffee, src/auditing.coffee, src/server.coffee, test/testUtils.coffee, test/unit/auditingTest.coffee
Opening PR so long but Travis needs fixing
=> External audit repo

config/default.json, src/api/audits.coffee, src/api/users.coffee, src/server.coffee
@rcrichton a quick one: I moved the audit source id into config
=> ATNA: Added option for setting the audit source id

docs/user-guide/basic-config.md, src/api/channels.coffee, src/middleware/router.coffee, src/model/channels.coffee, test/integration/channelsAPITests.coffee, test/integration/e2eIntegrationTests.coffee
=> OHM-225 Issue #613: Routes enable/disable

docs/user-guide/auditing.md, docs/user-guide/index.rst, docs/user-guide/polling-channels.md
@hnnesv could you please review these docs please.
=> Polling docs

src/metrics.coffee, src/reports.coffee
=> OHM-226 #599: Only add report data if channel is enabled or has data

docs/user-guide/basic-config.md, src/api/channels.coffee, src/middleware/authorisation.coffee, src/model/channels.coffee, test/integration/channelsAPITests.coffee, test/integration/e2eIntegrationTests.coffee, test/unit/authorisationTest.coffee
=> OHM-229 #612: Added channel priority functionality

config/default.json, src/api/users.coffee, src/contact.coffee, src/koaApi.coffee, src/model/users.coffee, test/integration/usersAPITests.coffee
This PR relates to issue: https://github.com/jembi/openhim-console/issues/310
=> Forgot password

infrastructure/development/env/openhim-core-js.pp, src/middleware/router.coffee
=> Transfer encoding header

src/middleware/messageStore.coffee, test/unit/messageStoreTest.coffee
Closes #619 
@hnnesv could you please review this for me as well.
=> Ensure redirect response codes are handled

infrastructure/development/env/Vagrantfile
skipping CR (3-liner vagrant provision)
=> vagrant: provision apt-get update

src/middleware/router.coffee, test/unit/routerTest.coffee
Closes #644 
@rcrichton if you could please review? the location header wasn't copied correctly
=> Issue #644: Copy location header

src/middleware/messageStore.coffee
Hi @rcrichton, can you please review.
=> Handle error before logging

src/middleware/rewriteUrls.coffee, test/unit/rewriteUrlsTest.coffee
Closes #652 
@rcrichton mind taking a look? Just added in a fullUrl clause which is used in fhir bundles
=> Issue #652: Added support for rewriting fullUrl

package.json, src/middleware/tlsAuthentication.coffee
=> Add common root CAs to our https server

docs/how-to/how-to-install-on-windows.md, docs/how-to/index.rst
@rcrichton this is a win install guide.
@cseebregts could you please take a read through this as well? thanks
=> Add windows how-to

docs/how-to/how-to-install-on-windows.md
Hi @hnnesv, I have added IIS instructions and consolidated the how-to. Please, could you check to see if you happy with the consolidation?
=> Add IIS Instructions

docs/how-to/how-to-install-on-windows.md
Hey @hnnesv, I have added instructions on how to run OpenHIM as a Windows Service
=> Add instructions on how to run OpenHIM as a Windows Service

src/model/audits.coffee
OHM-246
That easy :) tested on uct staging and saw an immediate improvement
=> OHM-246: Audits - added index for event timestamp

src/api/audits.coffee, src/auditing.coffee, src/model/audits.coffee, test/integration/auditAPITests.coffee, test/unit/auditingTest.coffee
=> OHM-247: Add audit meta collection to store filter fields for lookup

src/api/authentication.coffee, src/api/users.coffee, test/integration/authenticationAPITests.coffee
Add auditing exemption paths
OHM-248
=> OHM-248: Move auditing into authentication middleware

src/middleware/basicAuthentication.coffee, src/middleware/tlsAuthentication.coffee
@hnnesv could you please review this? I can't figure out an easy way to test this without it being more trouble than the actual code change. Let me know what you think.
=> Adds a client ID header to forwarded requests

test/globalConfig.coffee, test/integration/auditAPITests.coffee, test/integration/authenticationAPITests.coffee
@hnnesv please review. These are some changes to try improve test stability.
=> Adds setTimeouts for audit tests and test logging

test/integration/auditAPITests.coffee, test/integration/auditingIntegrationTests.coffee, test/integration/mediatorAPITests.coffee
I think this fixes #726, #727 and #728.  @rcrichton or @hnnesv can you please review.
=> Investigate ci test failures

docs/dev-guide/api-ref.md, src/api/visualizers.coffee, src/koaApi.coffee, src/model/events.coffee, src/model/transactions.coffee, src/model/visualizer.coffee, test/integration/visualizersAPITests.coffee, test/unit/visualizerModelTest.coffee
This PR includes the changes in #764 as it depends on these. Once that is merged in you will get a truer diff of the changes that are only for the endpoint. For now, you can just review the latest commit.
=> OHM-295 get visualizer API endpoint

resources/rotate-log.sh
@rcrichton a quick one not linked to a ticket. This is just a simple log rotation script. Maybe we should think about bundling this with the deb's?
cc @armageddon
=> Add log rotate script

src/autoRetry.coffee, test/unit/autoRetryTest.coffee
Note that this PR was branch from `ohm-279-error-results` (PR #767)
=> Ohm 280 single task

docs/user-guide/basic-config.md, src/alerts.coffee, src/koaMiddleware.coffee, src/middleware/events.coffee, src/middleware/messageStore.coffee, src/middleware/rerunUpdateTransactionTask.coffee, src/middleware/router.coffee, src/model/alerts.coffee, src/model/channels.coffee, src/model/events.coffee, src/model/transactions.coffee, test/integration/autoRetryIntegrationTests.coffee, test/integration/tasksAPITests.coffee, test/unit/alertsTest.coffee, test/unit/rerunUpdateTransactionTask.coffee
=> Ohm 281 max retry

src/api/visualizers.coffee
@rcrichton just a quick one I noticed while reviewing https://github.com/jembi/openhim-console/pull/415
apologies I should've pick this when reviewing #782
=> Fix user name in log

src/autoRetry.coffee, src/middleware/messageStore.coffee, src/model/autoRetry.coffee, src/model/transactions.coffee, test/integration/autoRetryIntegrationTests.coffee, test/unit/autoRetryTest.coffee
=> OHM-319: Add auto-retry queue

config/config.md, config/default.json, config/test.json, docs/dev-guide/api-ref.md, src/api/transactions.coffee, test/integration/transactionsAPITests.coffee
=> OHM-328: Add fulltruncate query mode for transactions

docs/user-guide/polling-channels.md, package.json, src/api/about.coffee, src/polling.coffee, src/reports.coffee, src/server.coffee, src/utils.coffee, test/unit/utilsTest.coffee
Agenda was defaulting to UTC timezone and not using the timezone of the server. Agenda tasks will now executing in the servers' timezone
=> OHM-360: Fix Agenda timezone issue

docs/user-guide/certificates.md
* consider forexample attempting to resolve: https://jembiprojects.jira.com/browse/OHM-382
=> OHM-429: Mentioning about keystore is helpful to the devs

config/default.json
Jira ticket: https://jembiprojects.jira.com/browse/OHM-448
=> Add new config options

config/default.json, src/utils.js
Jira Ticket: https://jembiprojects.jira.com/browse/OHM-449
=> Add function for mongo config

src/api/roles.js, test/integration/rolesAPITests.js
Adding roles now properly checks to see if it has channels and clients
Can't 'Delete' a role by updating with empty client and channels
=> Ohm 561 564 565 roles

config/default.json, package.json, performance/seed.js, src/api/channels.js, src/bodyCull.js, src/model/channels.js, src/server.js, test/integration/channelsAPITests.js, test/unit/bodyCullTest.js
=> Ohm 493 transaction cleanup

docs/about.md, docs/dev-guide/api-ref.md, docs/dev-guide/design-details.md, docs/dev-guide/design-overview.md, docs/dev-guide/getting-started-dev.md, docs/dev-guide/mediators.md, docs/how-to/how-to-install-on-ubuntu-trusty.md, docs/how-to/how-to-install-on-windows.md, docs/implementations/mhero.md, docs/implementations/momconnect.md, docs/tutorial/1-getting-started.md, docs/tutorial/2-creating-a-channel.md, docs/user-guide/adding-users.md, docs/user-guide/basic-config.md, docs/user-guide/mediators.md
Links have changed in the projects so references needed to be updated
OHM-584
=> Fix or remove broken links

docs/dev-guide/getting-started-dev.md, docs/dev-guide/mediators.md, docs/how-to/how-to-do-an-openhim-core-release.md, docs/how-to/how-to-install-on-ubuntu-trusty.md, docs/how-to/how-to-run-the-openhim-using-vagrant.md, docs/tutorial/1-getting-started.md, docs/tutorial/2-creating-a-channel.md, docs/user-guide/auditing.md, docs/user-guide/basic-config.md, docs/user-guide/mediators.md
Relative URLs were a bit off
OHM-584
=> Correct URLs... again

test/integration/auditAPITests.js, test/integration/auditingIntegrationTests.js, test/integration/authenticationAPITests.js, test/integration/mediatorAPITests.js, test/integration/routesTests.js, test/integration/tcpIntegrationTests.js, test/unit/upgradeDBTest.js
To account for race conditions
OHM-621
=> Add polling to failing tests

package-lock.json, src/metrics.js, test/unit/metricsTest.js
=> Updated a metrics check that verifies the timestamp value to check that its a object (Date) instead of a number

config/default.json
https://jembiprojects.jira.com/browse/OHM-678
=> Change the time between task running from 5 to 60 minutes

package-lock.json, src/alerts.js
so that transaction links in the alert emails redirect to the right page
OHM-677 OHM-654
=> add a shebang character to the url of the transaction link

src/middleware/messageStore.js, src/middleware/router.js, test/unit/messageStoreTest.js, test/unit/routerTest.js
so that metrics are created with mediators
OHM-684
=> update the 'update' object which is checked when creating metrics

.travis.yml
This is so we can get slack notifications on travis builds
OHM-713 OHM-670
=> add notification settings to the travis yml file

CHANGELOG.md, package-lock.json, package.json
Bump package version to reflect the version the OpenHIM core is on
Add a CHANGELOG file to track changes made between version
=> Ohm 737 release openhim core

README.md, infrastructure/centos/build-docker-centos-rpm.sh, packaging/README.md, packaging/build-docker-centos-rpm.sh
=> Created a bash build script for generating the RPM package based on a released version

CHANGELOG.md, package-lock.json, package.json
This is the final release
OHM-751 OHM-748
=> update the changelog and change the openhim version to 5.0.0

config/config.md, config/default.json, config/test.json, src/api/authentication.js, test/integration/authenticationAPITests.js
To simplify the authentication between other services and the OpenHIM
API.
=> Support basic auth for API calls

docs/user-guide/basic-config.md
Previously the note stated that the field 'excepts' a Regex 
value. It should be 'accepts'
=> Minor fix to url pattern note

package.json, src/contentChunk.js, test/unit/contentChunk.js
Clear database for gridfs for each test
OHM-763
=> Minor refactoring updates

package-lock.json, src/contentChunk.js, test/unit/contentChunk.js
this is for the route bodies
OHM-783
=> add logic for removing outdated payloads

src/koaMiddleware.js, src/middleware/events.js, src/middleware/requestMatching.js, src/middleware/rewriteUrls.js, src/middleware/router.js, test/integration/eventsAPITests.js, test/integration/httpTests.js, test/integration/transactionsAPITests.js, test/integration/urlRewriting.js, test/unit/requestMatchingTest.js, test/unit/rewriteUrlsTest.js
=> request and response streaming

src/koaMiddleware.js, src/middleware/messageStore.js, src/middleware/router.js, src/model/transactions.js
PR to investigate and add streaming to GridFS and downstream, and updating transaction after response
=> OHM-785 receive request stream

src/middleware/streamingRouter.js
1. When a timeout occurs in makeStreamingRequest, the promise should reject with an appropriate error object
2. Rerunning GET transactions is broken and needs to be fixed
=> Bug fix timeout promise parameter

src/koaMiddleware.js, src/middleware/rewriteUrls.js, src/middleware/router.js, src/middleware/streamingRouter.js, src/tasks.js, test/unit/rewriteUrlsTest.js
URL rewriting permits the HIM to rewrite URLs that occur in the response body before passing the body back up to the invoking client.
=> OHM-829 Add back URL rewriting functionality

CHANGELOG.md, package-lock.json, package.json
Updated Changelog to describe new changes in this version
OHM-939
=> Bump package version for new release

src/api/clients.js, src/model/clients.js, test/integration/clientsAPITests.js
Last few changes for Custom Token Auth
=> TRACE-136 custom tokens

README.md, src/api/transactions.js, src/contentChunk.js, src/koaApi.js, test/integration/transactionsAPITests.js, test/unit/contentChunk.js
Docs PR: https://github.com/jembi/openhim-docs/pull/44
=> OHM-1037 - new transaction bodies endpoint

src/api/transactions.js
This header will be used to determine whether the whole body has been retrieved
OHM-1039
=> send back the content-range header

package-lock.json, package.json
Fixed the Channel names bug in the email reports
=> Bump package patch version

CHANGELOG.md, package-lock.json, package.json, packaging/README.md
Reflect the node support changes
DATO-3
=> Update major version to v7

package.json, src/middleware/authorisation.js, src/middleware/requestMatching.js, test/integration/authenticationAPITests.js, test/integration/autoRetryIntegrationTests.js, test/integration/channelsAPITests.js, test/integration/eventsAPITests.js, test/integration/httpTests.js, test/integration/mediatorAPITests.js, test/integration/multipartFormDataTests.js, test/integration/routesTests.js, test/integration/urlRewriting.js, test/unit/requestMatchingTest.js
THis enables requests to be differentiated using the http method
OHM-1078
=> Add logic for matching the request http method

src/api/audits.js, test/integration/auditAPITests.js
To prevent special characters being used in the patientID field (fix a bug)
OHM-1084 OHM-927
=> OHM-1084 Update core validation for audit log patientID filter

package-lock.json, package.json
To keep the version in sync with the Github and docker releases PLAT-644
=> Update the version for release of SSO work

grafana-dashboards/openhim_nodejs_dashboard.json, grafana-dashboards/openhim_transactions_dashboard.json, package-lock.json, package.json, src/api/metrics.js, src/koaApi.js, src/metrics.js, test/integration/metricsAPITests.js, test/unit/metricsTest.js
Creates a prometheus exporter endpoint in the OpenHIM to allow metrics to be scraped by Prometheus. The PR also includes some default OpenHIM dashboards that can be used in grafana to visualise the prometheus metrics.
=> Prometheus exporter for OpenHIM

.travis.yml, config/config.md, config/default.json, docker-compose.deps.yml, package-lock.json, package.json, src/jwksCache.js, src/koaMiddleware.js, src/middleware/jwtAuthentication.js, test/unit/jwksCacheTest.js, test/unit/jwtAuthenicationTest.js
This pull request adds the jwks-rsa dependency and implements the jwksCache and auth modules. It also handles the public key not found error in the jwtAuthentication middleware. Additionally, a unit test has been added to ensure the functionality of the jwksCache module.
=> Add jwks-rsa dependency and implement jwksCache and auth
